kind: pipeline
name: droneciintegration

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: 58.87.112.192/lamondlu/app1
    registry: 58.87.112.192:6000
    dockerfile: dockerfile
  when:
  event:
  - push
  - pull-request     