kind: pipeline
name: droneciintegration

steps:
- name: build
  image: mcr.microsoft.com/dotnet/core/runtime:2.2
  commands:
  - dotnet restore
  - dotnet run 
  when:
  event:
  - push
  - pull-request      