kind: pipeline
name: droneciintegration

steps:
- name: build
  image: microsoft/aspnetcore-build
  commands:
  - dotnet restore
  - dotnet run 
  when:
  event:
  - push
  - pull-request     
  
services:
- name: myApp
  image: microsoft/aspnetcore-build